# netlify.toml
[build]
  # Set the base directory for your build process, if needed
  # base = "path/to/base/directory"

  # Command to build your site, adjust if you have a build step
  command = "npm run build"

  # Directory where your built files are located
  publish = "public"

# Redirects configuration
[[redirects]]
  from = "/npm/*"
  to = "/api/npm/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/yarn/*"
  to = "/api/yarn/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pnpm/*"
  to = "/api/pnpm/:splat"
  status = 200
  force = true

# If using functions for API endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Optional: Handle custom error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
